import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Nav & Layout
    'nav.home': 'Home',
    'nav.farms': 'Farms',
    'nav.weather': 'Weather',
    'nav.ai': 'AI Predictions',
    'nav.insurance': 'Insurance',
    'nav.schemes': 'Schemes',
    'nav.alerts': 'Alerts',
    'nav.satellite': 'Satellite',
    'nav.admin': 'Admin Panel',
    'nav.review': 'Insurance Review',
    'nav.market': 'Market Prices',
    'nav.logout': 'Logout',
    'nav.aiPlatform': 'AI PLATFORM',

    // Dashboard
    'dashboard.title': 'Farm Intelligence Overview',
    'dashboard.welcome': 'Welcome back',
    'dashboard.totalFarms': 'Total Farms',
    'dashboard.avgHealth': 'Avg Health Score',
    'dashboard.activePolicies': 'Active Policies',
    'dashboard.alerts': 'Active Alerts',

    // Farms
    'farms.title': 'My Farms',
    'farms.registered': 'farms registered',
    'farms.addFarm': 'Add Farm',
    'farms.noFarms': 'No farms yet',
    'farms.noFarmsDesc': 'Register your first farm to start monitoring crop health with satellite data and AI predictions.',
    'farms.registerFirst': 'Register Your First Farm',
    'farms.healthScore': 'health score',
    'farms.crop': 'Crop',
    'farms.size': 'Size',
    'farms.soil': 'Soil',
    'farms.delete': 'Delete',
    'farms.deleteConfirm': 'Are you sure you want to delete',
    'farms.deleteWarning': 'This action cannot be undone.',
    'farms.deleted': 'Farm deleted successfully',

    // Add Farm
    'addFarm.title': 'Register New Farm',
    'addFarm.subtitle': 'Add farm details and set location — soil & weather data auto-fetched',
    'addFarm.setLocation': 'Set Farm Location',
    'addFarm.clickMap': 'Click on the map — soil, weather & location data will be fetched automatically',
    'addFarm.farmDetails': 'Farm Details',
    'addFarm.farmName': 'Farm Name',
    'addFarm.cropCategory': 'Crop Type',
    'addFarm.cropType': 'Specific Crop',
    'addFarm.farmSize': 'Farm Size (hectares)',
    'addFarm.soilType': 'Soil Type',
    'addFarm.irrigation': 'Irrigation Method',
    'addFarm.plantingDate': 'Planting Date',
    'addFarm.harvestDate': 'Expected Harvest',
    'addFarm.register': 'Register Farm',
    'addFarm.autoDetected': '(auto-detected)',
    'addFarm.suggested': '(suggested)',
    'addFarm.autoFilled': 'Soil type & irrigation auto-filled from location data. You can adjust them.',

    // Farm Detail
    'farmDetail.back': 'Back to Farms',
    'farmDetail.runAI': 'Run AI Analysis',
    'farmDetail.deleteFarm': 'Delete Farm',
    'farmDetail.healthScore': 'Health Score',
    'farmDetail.latestNDVI': 'Latest NDVI',
    'farmDetail.soilMoisture': 'Soil Moisture',
    'farmDetail.temperature': 'Temperature',
    'farmDetail.farmLocation': 'Farm Location',
    'farmDetail.ndviTrend': 'NDVI Trend (15 days)',
    'farmDetail.noSatData': 'No satellite data yet',
    'farmDetail.riskPredictions': 'AI Risk Predictions',
    'farmDetail.risk': 'Risk',
    'farmDetail.confidence': 'confidence',
    'farmDetail.predicted': 'Predicted',
    'farmDetail.satelliteData': 'Satellite Data',
    'farmDetail.weatherData': 'Weather Data',
    'farmDetail.aiPredictions': 'AI Predictions',
    'farmDetail.insurance': 'Insurance',

    // Insurance
    'insurance.title': 'Parametric Insurance',
    'insurance.subtitle': 'Automated crop insurance with parametric triggers',
    'insurance.enrollBtn': 'Enroll Policy',
    'insurance.totalCoverage': 'Total Coverage',
    'insurance.claimsFiled': 'Claims Filed',
    'insurance.payouts': 'Payouts',
    'insurance.noPolicies': 'No policies yet. Enroll in an insurance plan to protect your crops.',
    'insurance.enrollTitle': 'Enroll in Insurance',
    'insurance.farm': 'Farm',
    'insurance.policyType': 'Policy Type',
    'insurance.premium': 'Premium',
    'insurance.coverage': 'Coverage',
    'insurance.season': 'Season',
    'insurance.enrollNow': 'Enroll Now',
    'insurance.status': 'Status',
    'insurance.checkTriggers': 'Check Triggers',
    'insurance.claimsTitle': 'Insurance Claims',
    'insurance.noClaims': 'No claims yet. Claims are automatically triggered when conditions are met.',

    'market.title': 'Market Intelligence',
    'market.subtitle': 'Real-time commodity prices and market trends',
    'market.trendTitle': 'Price Trends',
    'market.sentiment': 'Market Sentiment',
    'market.sellingWindow': 'Best Selling Window',
    'market.region': 'Select Region',
    'market.allRegions': 'All Regions',
    'market.demand': 'Demand',
    'market.demand.high': 'High',
    'market.demand.medium': 'Medium',
    'market.demand.low': 'Low',
    'market.category.cash_crops': 'Cash Crops',
    'market.category.fruits': 'Fruits',

    'cropCategory.cereals': 'Cereals',
    'cropCategory.pulses': 'Pulses',
    'cropCategory.cash_crops': 'Cash Crops',
    'cropCategory.oilseeds': 'Oilseeds',
    'cropCategory.vegetables': 'Vegetables',
    'cropCategory.spices': 'Spices',
    'cropCategory.fruits': 'Fruits',
    'cropCategory.other': 'Other',

    'crop.rice': 'Rice',
    'crop.wheat': 'Wheat',
    'crop.maize': 'Maize',
    'crop.barley': 'Barley',
    'crop.millet': 'Millet',
    'crop.sorghum': 'Sorghum',
    'crop.bajra': 'Pearl Millet (Bajra)',
    'crop.ragi': 'Finger Millet (Ragi)',
    'crop.chickpea': 'Chickpea',
    'crop.lentil': 'Lentil',
    'crop.green_gram': 'Green Gram (Moong)',
    'crop.black_gram': 'Black Gram (Urad)',
    'crop.pigeon_pea': 'Pigeon Pea (Arhar)',
    'crop.soybean': 'Soybean',
    'crop.cotton': 'Cotton',
    'crop.sugarcane': 'Sugarcane',
    'crop.tobacco': 'Tobacco',
    'crop.coffee': 'Coffee',
    'crop.tea': 'Tea',
    'crop.rubber': 'Rubber',
    'crop.groundnut': 'Groundnut',
    'crop.sunflower': 'Sunflower',
    'crop.mustard': 'Mustard',
    'crop.sesame': 'Sesame',
    'crop.onion': 'Onion',
    'crop.potato': 'Potato',
    'crop.tomato': 'Tomato',
    'crop.chilli': 'Chilli',
    'crop.garlic': 'Garlic',
    'crop.turmeric': 'Turmeric',
    'crop.ginger': 'Ginger',
    'crop.cumin': 'Cumin',
    'crop.coriander': 'Coriander',
    'crop.okra': 'Okra (Bhindi)',
    'crop.spinach': 'Spinach',
    'crop.cabbage': 'Cabbage',
    'crop.cauliflower': 'Cauliflower',
    'crop.mango': 'Mango',
    'crop.banana': 'Banana',
    'crop.papaya': 'Papaya',
    'crop.guava': 'Guava',
    'crop.pomegranate': 'Pomegranate',
    'crop.lemon': 'Lemon',
    'crop.grapes': 'Grapes',
    'crop.coconut': 'Coconut',
    'crop.other': 'Other',


    // Insurer Review
    'review.title': 'Insurance Review Portal',
    'review.subtitle': 'Review pending applications and run AI analysis',
    'review.analyzeLand': 'Analyze Risk',
    'review.approve': 'Approve',
    'review.reject': 'Reject',
    'review.recommendation': 'AI Recommendation',
    'review.healthScore': 'Health Score',
    'review.risk': 'Risk',
    'review.locationPreview': 'Farm Location Preview',

    // Govt Schemes
    'schemes.title': 'Government Schemes',
    'schemes.subtitle': 'Access agricultural welfare programs and subsidies from the Government of India',
    'schemes.pmfby': 'Pradhan Mantri Fasal Bima Yojana',
    'schemes.pmfbyDesc': 'Comprehensive crop insurance scheme covering all food crops, oilseeds, and commercial/horticultural crops. Premium rates: 2% for Kharif, 1.5% for Rabi, 5% for commercial crops.',
    'schemes.enam': 'e-NAM (National Agriculture Market)',
    'schemes.enamDesc': 'Pan-India electronic trading portal connecting APMC mandis. Sell your produce online, get better prices, and access markets across India without middlemen.',
    'schemes.kcc': 'Kisan Credit Card',
    'schemes.kccDesc': 'Get affordable credit for crop production, post-harvest expenses, and farm maintenance. Interest rate as low as 4% p.a. with timely repayment. Loan up to ₹3 lakh.',
    'schemes.pmkisan': 'PM-KISAN',
    'schemes.pmkisanDesc': 'Direct income support of ₹6,000 per year in 3 installments to all land-holding farmer families. Register with Aadhaar and bank account.',
    'schemes.applyNow': 'Apply / Learn More',
    'schemes.eligibility': 'Eligibility',
    'schemes.benefits': 'Benefits',
    'schemes.documents': 'Documents Required',

    // Alerts
    'alerts.title': 'Alert Settings',
    'alerts.subtitle': 'Configure SMS and WhatsApp notifications for your farms',
    'alerts.phone': 'Phone Number',
    'alerts.phonePlaceholder': '+91 98765 43210',
    'alerts.whatsapp': 'Enable WhatsApp Alerts',
    'alerts.sms': 'Enable SMS Alerts',
    'alerts.weatherAlerts': 'Weather Alerts',
    'alerts.weatherDesc': 'Get notified about extreme weather conditions affecting your farms',
    'alerts.riskAlerts': 'Risk Alerts',
    'alerts.riskDesc': 'Get notified when AI detects high risk for drought, flood, or disease',
    'alerts.priceAlerts': 'Market Price Alerts',
    'alerts.priceDesc': 'Daily market price updates for your crops from e-NAM',
    'alerts.schemeAlerts': 'Govt Scheme Updates',
    'alerts.schemeDesc': 'New scheme announcements and deadline reminders',
    'alerts.save': 'Save Alert Settings',
    'alerts.saved': 'Alert settings saved!',
    'alerts.testSent': 'Test alert sent!',
    'alerts.sendTest': 'Send Test',

    // Common
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.language': 'Language',

    // Soil types
    'soil.clay': 'Clay', 'soil.sandy': 'Sandy', 'soil.loamy': 'Loamy', 'soil.silt': 'Silt', 'soil.peat': 'Peat', 'soil.chalk': 'Chalk', 'soil.other': 'Other',
    // Crops
    'crop.rice': 'Rice', 'crop.wheat': 'Wheat', 'crop.corn': 'Corn', 'crop.cotton': 'Cotton', 'crop.sugarcane': 'Sugarcane', 'crop.soybean': 'Soybean', 'crop.other': 'Other',
    // Irrigation
    'irr.rainfed': 'Rainfed', 'irr.drip': 'Drip', 'irr.sprinkler': 'Sprinkler', 'irr.flood': 'Flood', 'irr.canal': 'Canal', 'irr.other': 'Other',
  },

  hi: {
    'nav.home': 'होम',
    'nav.farms': 'खेत',
    'nav.weather': 'मौसम',
    'nav.ai': 'AI पूर्वानुमान',
    'nav.insurance': 'बीमा',
    'nav.schemes': 'योजनाएं',
    'nav.alerts': 'अलर्ट',
    'nav.satellite': 'उपग्रह',
    'nav.admin': 'एडमिन पैनल',
    'nav.review': 'बीमा समीक्षा',
    'nav.logout': 'लॉगआउट',
    'nav.aiPlatform': 'AI प्लेटफॉर्म',

    'dashboard.welcome': 'स्वागत है',
    'dashboard.title': 'फार्म इंटेलिजेंस ओवरव्यू',
    'dashboard.totalFarms': 'कुल फार्म',
    'dashboard.avgHealth': 'औसत स्वास्थ्य स्कोर',
    'dashboard.activePolicies': 'सक्रिय नीतियां',
    'dashboard.alerts': 'सक्रिय अलर्ट',

    'farms.title': 'मेरे खेत',
    'farms.registered': 'पंजीकृत खेत',
    'farms.addFarm': 'खेत जोड़ें',
    'farms.noFarms': 'अभी तक कोई खेत नहीं',
    'farms.noFarmsDesc': 'उपग्रह डेटा और AI पूर्वानुमान के साथ फसल स्वास्थ्य की निगरानी शुरू करने के लिए अपना पहला खेत पंजीकृत करें।',
    'farms.registerFirst': 'अपना पहला खेत पंजीकृत करें',
    'farms.healthScore': 'स्वास्थ्य स्कोर',
    'farms.crop': 'फसल',
    'farms.size': 'आकार',
    'farms.soil': 'मिट्टी',
    'farms.delete': 'हटाएं',
    'farms.deleteConfirm': 'क्या आप वाकई हटाना चाहते हैं',
    'farms.deleteWarning': 'यह क्रिया पूर्ववत नहीं की जा सकती।',
    'farms.deleted': 'खेत सफलतापूर्वक हटाया गया',

    'addFarm.title': 'नया खेत पंजीकृत करें',
    'addFarm.subtitle': 'खेत का विवरण जोड़ें और स्थान सेट करें — मिट्टी और मौसम डेटा स्वचालित',
    'addFarm.setLocation': 'खेत का स्थान सेट करें',
    'addFarm.clickMap': 'मानचित्र पर क्लिक करें — मिट्टी, मौसम और भू-डेटा स्वचालित रूप से प्राप्त होगा',
    'addFarm.farmDetails': 'खेत विवरण',
    'addFarm.cropCategory': 'फसल प्रकार',
    'addFarm.cropType': 'विशिष्ट फसल',
    'addFarm.farmSize': 'खेत का आकार (हेक्टेयर)',
    'addFarm.soilType': 'मिट्टी का प्रकार',
    'addFarm.irrigation': 'सिंचाई विधि',
    'addFarm.plantingDate': 'बुवाई की तारीख',
    'addFarm.harvestDate': 'अपेक्षित कटाई',
    'addFarm.register': 'खेत पंजीकृत करें',

    'farmDetail.back': 'खेतों पर वापस',
    'farmDetail.runAI': 'AI विश्लेषण चलाएं',
    'farmDetail.deleteFarm': 'खेत हटाएं',
    'farmDetail.healthScore': 'स्वास्थ्य स्कोर',
    'farmDetail.latestNDVI': 'नवीनतम NDVI',
    'farmDetail.soilMoisture': 'मिट्टी की नमी',
    'farmDetail.temperature': 'तापमान',
    'farmDetail.farmLocation': 'खेत का स्थान',
    'farmDetail.ndviTrend': 'NDVI रुझान (15 दिन)',
    'farmDetail.noSatData': 'अभी कोई उपग्रह डेटा नहीं',
    'farmDetail.riskPredictions': 'AI जोखिम पूर्वानुमान',
    'farmDetail.satelliteData': 'उपग्रह डेटा',
    'farmDetail.weatherData': 'मौसम डेटा',
    'farmDetail.aiPredictions': 'AI पूर्वानुमान',
    'farmDetail.insurance': 'बीमा',

    'insurance.title': 'पैरामीट्रिक बीमा',
    'insurance.subtitle': 'पैरामीट्रिक ट्रिगर्स के साथ स्वचालित फसल बीमा',
    'insurance.enrollBtn': 'पॉलिसी नामांकित करें',
    'insurance.totalCoverage': 'कुल कवरेज',
    'insurance.claimsFiled': 'दायर किए गए दावे',
    'insurance.payouts': 'भुगतान',
    'insurance.noPolicies': 'अभी तक कोई नीति नहीं है। नामांकन करें।',
    'insurance.enrollTitle': 'बीमा में नामांकन करें',
    'insurance.farm': 'फार्म',
    'insurance.policyType': 'पॉलिसी प्रकार',
    'insurance.premium': 'प्रीमियम',
    'insurance.coverage': 'कवरेज',
    'insurance.season': 'सीजन',
    'insurance.enrollNow': 'अभी नामांकन करें',
    'insurance.status': 'स्थिति',
    'insurance.checkTriggers': 'ट्रिगर्स की जाँच करें',
    'insurance.claimsTitle': 'बीमा दावे',
    'insurance.noClaims': 'अभी तक कोई दावा नहीं है।',

    'review.title': 'बीमा समीक्षा पोर्टल',
    'review.subtitle': 'लंबित आवेदनों की समीक्षा करें और AI विश्लेषण चलाएं',
    'review.analyzeLand': 'जोखिम विश्लेषण',
    'review.approve': 'स्वीकार करें',
    'review.reject': 'अस्वीकार करें',
    'review.recommendation': 'AI अनुशंसा',
    'review.healthScore': 'स्वास्थ्य स्कोर',
    'review.risk': 'जोखिम',
    'review.locationPreview': 'फार्म स्थान पूर्वावलोकन',

    'schemes.title': 'सरकारी योजनाएं',
    'schemes.pmfby': 'प्रधानमंत्री फसल बीमा योजना',
    'schemes.enam': 'e-NAM (राष्ट्रीय कृषि बाजार)',
    'schemes.kcc': 'किसान क्रेडिट कार्ड',
    'schemes.pmkisan': 'पीएम-किसान',
    'schemes.applyNow': 'आवेदन करें',

    'alerts.title': 'अलर्ट सेटिंग्स',
    'alerts.phone': 'फोन नंबर',
    'alerts.save': 'सेव करें',
    'alerts.sendTest': 'टेस्ट भेजें',

    'market.title': 'बाजार इंटेलिजेंस',
    'market.subtitle': 'वास्तविक समय की वस्तु कीमतें और बाजार के रुझान',
    'market.trendTitle': 'मूल्य रुझान',
    'market.region': 'क्षेत्र चुनें',
    'market.allRegions': 'सभी क्षेत्र',
    'market.demand': 'मांग',
    'market.demand.high': 'उच्च',
    'market.demand.medium': 'मध्यम',
    'market.demand.low': 'कम',
    'market.category.all': 'सभी',
    'market.category.cereals': 'अनाज',
    'market.category.fiber': 'फाइबर',
    'market.category.oilseeds': 'तिलहन',
    'market.category.cash_crops': 'नकदी फसलें',
    'market.category.pulses': 'दालें',
    'market.category.spices': 'मसाले',
    'market.category.vegetables': 'सब्जियाँ',
    'market.category.fruits': 'फल',

    'cropCategory.cereals': 'अनाज',
    'cropCategory.pulses': 'दलहन (Pulses)',
    'cropCategory.cash_crops': 'नकदी फसलें',
    'cropCategory.oilseeds': 'तिलहन',
    'cropCategory.vegetables': 'सब्जियाँ',
    'cropCategory.spices': 'मसाले',
    'cropCategory.fruits': 'फल',
    'cropCategory.other': 'अन्य',

    'common.loading': 'लोड हो रहा है...',
    'common.language': 'भाषा',
    'soil.clay': 'चिकनी मिट्टी', 'soil.sandy': 'रेतीली', 'soil.loamy': 'दोमट',
    'crop.rice': 'चावल',
    'crop.wheat': 'गेहूं',
    'crop.maize': 'मक्का',
    'crop.barley': 'जौ (Barley)',
    'crop.millet': 'बाजरा',
    'crop.sorghum': 'ज्वार',
    'crop.bajra': 'बाजरा (Bajra)',
    'crop.ragi': 'रागी',
    'crop.chickpea': 'चना',
    'crop.lentil': 'मसूर',
    'crop.green_gram': 'मूंग',
    'crop.black_gram': 'उड़द',
    'crop.pigeon_pea': 'अरहर',
    'crop.soybean': 'सोयाबीन',
    'crop.cotton': 'कपास',
    'crop.sugarcane': 'गन्ना',
    'crop.tobacco': 'तंबाकू',
    'crop.coffee': 'कॉफी',
    'crop.tea': 'चाय',
    'crop.rubber': 'रबड़',
    'crop.groundnut': 'मूंगफली',
    'crop.sunflower': 'सूरजमुखी',
    'crop.mustard': 'सरसों',
    'crop.sesame': 'तिल',
    'crop.onion': 'प्याज',
    'crop.potato': 'आलू',
    'crop.tomato': 'टमाटर',
    'crop.chilli': 'मिर्च',
    'crop.garlic': 'लहसुन',
    'crop.turmeric': 'हल्दी',
    'crop.ginger': 'अदरक',
    'crop.cumin': 'जीरा',
    'crop.coriander': 'धनिया',
    'crop.okra': 'भिंडी',
    'crop.spinach': 'पालक',
    'crop.cabbage': 'पत्ता गोभी',
    'crop.cauliflower': 'फूलगोभी',
    'crop.mango': 'आम',
    'crop.banana': 'केला',
    'crop.papaya': 'पपीता',
    'crop.guava': 'अमरूद',
    'crop.pomegranate': 'अनार',
    'crop.lemon': 'नींबू',
    'crop.grapes': 'अंगूर',
    'crop.coconut': 'नारियल',
    'crop.other': 'अन्य',
    'irr.rainfed': 'वर्षा आधारित', 'irr.drip': 'ड्रिप', 'irr.sprinkler': 'स्प्रिंकलर',
  },

  ta: {
    'nav.home': 'முகப்பு',
    'nav.farms': 'பண்ணைகள்',
    'nav.weather': 'வானிலை',
    'nav.ai': 'AI கணிப்புகள்',
    'nav.insurance': 'காப்பீடு',
    'nav.schemes': 'திட்டங்கள்',
    'nav.alerts': 'அலர்ட்',
    'nav.satellite': 'செயற்கைக்கோள்',
    'nav.admin': 'நிர்வாகி',
    'nav.review': 'காப்பீடு மதிப்பாய்வு',
    'nav.logout': 'வெளியேறு',
    'nav.aiPlatform': 'AI தளம்',

    'dashboard.welcome': 'வரவேற்கிறோம்',
    'dashboard.title': 'பண்ணை மேலோட்டம்',
    'dashboard.totalFarms': 'மொத்த பண்ணைகள்',
    'dashboard.avgHealth': 'சராசரி ஆரோக்கியம்',
    'dashboard.activePolicies': 'செயலில் உள்ள காப்பீடு',
    'dashboard.alerts': 'செயலில் உள்ள அலர்ட்',

    'farms.title': 'என் பண்ணைகள்',
    'farms.registered': 'பதிவு செய்யப்பட்டவை',
    'farms.addFarm': 'பண்ணை சேர்',
    'farms.healthScore': 'ஆரோக்கிய மதிப்பெண்',
    'farms.crop': 'பயிர்',
    'farms.size': 'அளவு',

    'addFarm.farmName': 'பண்ணை பெயர்',
    'addFarm.cropCategory': 'பயிர் வகை',
    'addFarm.cropType': 'குறிப்பிட்ட பயிர்',
    'addFarm.farmSize': 'பண்ணை அளவு (हेक्टेयर)',

    'insurance.title': 'பயிர் காப்பீடு',
    'insurance.subtitle': 'தானியங்கி பயிர் காப்பீடு',
    'insurance.enrollBtn': 'பதிவு செய்',
    'insurance.totalCoverage': 'மொத்த கவரேஜ்',
    'insurance.enrollTitle': 'காப்பீட்டில் பதிவு செய்க',
    'insurance.status': 'நிலை',
    'insurance.checkTriggers': 'சரிபார்க்கவும்',

    'review.title': 'காப்பீடு மதிப்பாய்வு',
    'review.subtitle': 'விண்ணப்பங்களை மதிப்பாய்வு செய்யவும்',
    'review.analyzeLand': 'ஆய்வு செய்',
    'review.approve': 'அனுமதி',
    'review.reject': 'நிராகரி',
    'review.healthScore': 'ஆரோக்கிய மதிப்பெண்',

    'common.language': 'மொழி',
    'soil.clay': 'களிமண்', 'soil.sandy': 'மணல்', 'soil.loamy': 'வண்டல்',
    'crop.rice': 'அரிசி',
    'crop.wheat': 'கோதுமை',
    'crop.maize': 'சோளம்',
    'crop.barley': 'பார்லி',
    'crop.millet': 'சிறுதானியம்',
    'crop.sorghum': 'சோளம் (Jowar)',
    'crop.bajra': 'கம்பு',
    'crop.ragi': 'கேழ்வரகு',
    'crop.chickpea': 'கொண்டைக்கடலை',
    'crop.lentil': 'பருப்பு',
    'crop.green_gram': 'பாசிப்பயறு',
    'crop.black_gram': 'உளுந்து',
    'crop.pigeon_pea': 'துவரம் பருப்பு',
    'crop.soybean': 'சோயாபீன்',
    'crop.cotton': 'பருத்தி',
    'crop.sugarcane': 'கரும்பு',
    'crop.tobacco': 'புகையிலை',
    'crop.coffee': 'காபி',
    'crop.tea': 'தேயிலை',
    'crop.rubber': 'ரப்பர்',
    'crop.groundnut': 'நிலக்கடலை',
    'crop.sunflower': 'சூரியகாந்தி',
    'crop.mustard': 'கடுகு',
    'crop.sesame': 'எள்',
    'crop.onion': 'வெங்காயம்',
    'crop.potato': 'உருளைக்கிழங்கு',
    'crop.tomato': 'தக்காளி',
    'crop.chilli': 'மிளகாய்',
    'crop.garlic': 'பூண்டு',
    'crop.turmeric': 'மஞ்சள்',
    'crop.ginger': 'இஞ்சி',
    'crop.cumin': 'சீரகம்',
    'crop.coriander': 'கொத்தமல்லி',
    'crop.okra': 'வெண்டைக்காய்',
    'crop.spinach': 'கீரை',
    'crop.cabbage': 'முட்டைக்கோஸ்',
    'crop.cauliflower': 'காலிஃபிளவர்',
    'crop.mango': 'மாம்பழம்',
    'crop.banana': 'வாழைப்பழம்',
    'crop.papaya': 'பப்பாளி',
    'crop.guava': 'கொய்யா',
    'crop.pomegranate': 'மாதுளை',
    'crop.lemon': 'எலுமிச்சை',
    'crop.grapes': 'திராட்சை',
    'crop.coconut': 'தேங்காய்',
    'crop.other': 'மற்றவை',
    'market.title': 'சந்தை நுண்ணறிவு',
    'market.subtitle': 'உண்மையான நேர விலை மற்றும் சந்தை போக்குகள்',
    'market.trendTitle': 'விலை போக்குகள்',
    'market.region': 'பிராந்தியத்தைத் தேர்வுசெய்க',
    'market.allRegions': 'அனைத்து பிராந்தியங்களும்',
    'market.demand': 'தேவை',
    'market.demand.high': 'அதிகம்',
    'market.demand.medium': 'நடுத்தரம்',
    'market.demand.low': 'குறைவு',
    'market.category.all': 'அனைத்தும்',
    'market.category.cereals': 'தானியங்கள்',
    'market.category.fiber': 'நார்',
    'market.category.oilseeds': 'எண்ணெய் வித்துக்கள்',
    'market.category.cash_crops': 'வணிகப் பயிர்கள்',
    'market.category.pulses': 'பருப்பு வகைகள்',
    'market.category.spices': 'மசாலாப் பொருட்கள்',
    'market.category.vegetables': 'காய்கறிகள்',
    'market.category.fruits': 'பழங்கள்',

    'cropCategory.cereals': 'தானியங்கள்',
    'cropCategory.pulses': 'பருப்பு வகைகள்',
    'cropCategory.cash_crops': 'வணிகப் பயிர்கள்',
    'cropCategory.oilseeds': 'எண்ணெய் வித்துக்கள்',
    'cropCategory.vegetables': 'காய்கறிகள்',
    'cropCategory.spices': 'மசாலாப் பொருட்கள்',
    'cropCategory.fruits': 'பழங்கள்',
    'cropCategory.other': 'மற்றவை',

    'irr.rainfed': 'மழை நீர்', 'irr.drip': 'சொட்டு நீர்', 'irr.sprinkler': 'தெளிப்பான்',
  },

  te: {
    'nav.home': 'హోమ్',
    'nav.farms': 'పొలాలు',
    'nav.weather': 'వాతావరణం',
    'nav.ai': 'AI అంచనాలు',
    'nav.insurance': 'భీమా',
    'nav.schemes': 'పథకాలు',
    'nav.alerts': 'అలర్ట్లు',
    'nav.review': 'భీమా సమీక్ష',
    'nav.logout': 'లాగ్‌అవుట్',

    'dashboard.welcome': 'స్వాగతం',
    'dashboard.totalFarms': 'మొత్తం ఫామ్స్',
    'dashboard.avgHealth': 'సగటు ఆరోగ్య స్కోరు',

    'addFarm.farmName': 'ఫామ్ పేరు',
    'addFarm.cropCategory': 'పంట రకం',
    'addFarm.cropType': 'నిర్దిష్ట పంట',
    'addFarm.farmSize': 'ఫామ్ పరిమాణం (హెక్టార్లు)',

    'insurance.title': 'పంట భీమా',
    'insurance.enrollBtn': 'నమోదు చేయండి',
    'insurance.status': 'స్థితి',

    'review.title': 'భీమా సమీక్ష',
    'review.approve': 'ఆమోదించు',
    'review.reject': 'తిరస్కరించు',

    'common.loading': 'లోడ్ అవుతోంది...',
    'common.language': 'భాష',
    'soil.clay': 'బంకమట్టి', 'soil.sandy': 'ఇసుక', 'soil.loamy': 'దుమ్ము',
    'crop.rice': 'వరి',
    'crop.wheat': 'గోధుమ',
    'crop.maize': 'మొక్కజొన్న',
    'crop.barley': 'యవలు (Barley)',
    'crop.millet': 'చిరుధాన్యాలు',
    'crop.sorghum': 'జొన్నలు',
    'crop.bajra': 'సజ్జలు',
    'crop.ragi': 'రాగులు',
    'crop.chickpea': 'శనగలు',
    'crop.lentil': 'మసూర్ పప్పు',
    'crop.green_gram': 'పెసలు',
    'crop.black_gram': 'మినుములు',
    'crop.pigeon_pea': 'కందులు',
    'crop.soybean': 'సోయాబీన్',
    'crop.cotton': 'పత్తి',
    'crop.sugarcane': 'చెరకు',
    'crop.tobacco': 'పొగాకు',
    'crop.coffee': 'కాఫీ',
    'crop.tea': 'తేయాకు',
    'crop.rubber': 'రబ్బరు',
    'crop.groundnut': 'వేరుశనగ',
    'crop.sunflower': 'పొద్దుతిరుగుడు',
    'crop.mustard': 'ఆవాలు',
    'crop.sesame': 'నువ్వులు',
    'crop.onion': 'ఉల్లిపాయ',
    'crop.potato': 'బంగాళాదుంప',
    'crop.tomato': 'టమాటా',
    'crop.chilli': 'మిర్చి',
    'crop.garlic': 'వెల్లుల్లి',
    'crop.turmeric': 'పసుపు',
    'crop.ginger': 'అల్లం',
    'crop.cumin': 'జీలకర్ర',
    'crop.coriander': 'ధనియాలు',
    'crop.okra': 'బెండకాయ',
    'crop.spinach': 'పాలకూర',
    'crop.cabbage': 'క్యాబేజీ',
    'crop.cauliflower': 'కాలీఫ్లవర్',
    'crop.mango': 'మామిడి',
    'crop.banana': 'అరటి',
    'crop.papaya': 'బొప్పాయి',
    'crop.guava': 'జామ',
    'crop.pomegranate': 'దానిమ్మ',
    'crop.lemon': 'నిమ్మ',
    'crop.grapes': 'ద్రాక్ష',
    'crop.coconut': 'కొబ్బరి',
    'crop.other': 'ఇతర',
    'market.title': 'మార్కెట్ ఇంటెలిజెన్స్',
    'market.subtitle': 'రియల్ టైమ్ వస్తువుల ధరలు మరియు మార్కెట్ ట్రెండ్స్',
    'market.trendTitle': 'ధర ట్రెండ్స్',
    'market.region': 'ప్రాంతాన్ని ఎంచుకోండి',
    'market.allRegions': 'అన్ని ప్రాంతాలు',
    'market.demand': 'డిమాండ్',
    'market.demand.high': 'ఎక్కువ',
    'market.demand.medium': 'మధ్యస్థం',
    'market.demand.low': 'తక్కువ',
    'market.category.all': 'అన్నీ',
    'market.category.cereals': 'ధాన్యాలు',
    'market.category.fiber': 'పీచు',
    'market.category.oilseeds': 'నూనె గింజలు',
    'market.category.cash_crops': 'వాణిజ్య పంటలు',
    'market.category.pulses': 'పప్పుధాన్యాలు',
    'market.category.spices': 'మసాలా దినుసులు',
    'market.category.vegetables': 'కూరగాయలు',
    'market.category.fruits': 'పండ్లు',

    'cropCategory.cereals': 'ధాన్యాలు',
    'cropCategory.pulses': 'పప్పుధాన్యాలు',
    'cropCategory.cash_crops': 'వాణిజ్య పంటలు',
    'cropCategory.oilseeds': 'నూనె గింజలు',
    'cropCategory.vegetables': 'కూరగాయలు',
    'cropCategory.spices': 'మసాలా దినుసులు',
    'cropCategory.fruits': 'పండ్లు',
    'cropCategory.other': 'ఇతర',

    'irr.rainfed': 'వర్షాధార', 'irr.drip': 'బిందు సేద్యం', 'irr.sprinkler': 'స్ప్రింక్లర్',
  }
};

const LANGUAGES = [
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'हिंदी', flag: '🇮🇳' },
  { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' },
  { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
];

const LanguageContext = createContext(null);

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('agrishield_lang') || 'en');

  const t = (key) => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  const changeLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('agrishield_lang', newLang);
  };

  return (
    <LanguageContext.Provider value={{ lang, t, changeLang, languages: LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};
